DROP TABLE IF EXISTS POST;

CREATE TABLE POST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  content VARCHAR(500) NOT NULL
);

DROP TABLE IF EXISTS TAG_TYPE;

CREATE TABLE TAG_TYPE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  tag_name VARCHAR(250) UNIQUE
);

DROP TABLE IF EXISTS POST_TAG;

CREATE TABLE POST_TAG (
  post_id INT,
  tag_id INT,
  FOREIGN KEY (post_id) REFERENCES POST (id),
  FOREIGN KEY (tag_id) REFERENCES TAG_TYPE (id),
  CONSTRAINT UC_PostsTags UNIQUE (post_id, tag_id)
);

